export declare const SocketEvents: Readonly<{
  readonly QUEUE_JOIN: 'queue:join';
  readonly QUEUE_LEAVE: 'queue:leave';
  readonly GAME_JOIN: 'game:join';
  readonly GAME_MOVE: 'game:move';
  readonly GAME_RESIGN: 'game:resign';
  readonly GAME_OFFER_DRAW: 'game:offerDraw';
  readonly GAME_ACCEPT_DRAW: 'game:acceptDraw';
  readonly GAME_DECLINE_DRAW: 'game:declineDraw';
  readonly GAME_SYNC_REQUEST: 'game:syncRequest';
  readonly GAME_REMATCH_REQUEST: 'game:rematchRequest';
  readonly GAME_REMATCH_ACCEPT: 'game:rematchAccept';
  readonly GAME_REMATCH_DECLINE: 'game:rematchDecline';
  readonly PRESENCE_PING: 'presence:ping';
  readonly QUEUE_JOINED: 'queue:joined';
  readonly QUEUE_LEFT: 'queue:left';
  readonly MATCH_FOUND: 'match:found';
  readonly GAME_JOINED: 'game:joined';
  readonly GAME_STATE: 'game:state';
  readonly GAME_MOVE_ACCEPTED: 'game:moveAccepted';
  readonly GAME_MOVE_REJECTED: 'game:moveRejected';
  readonly GAME_CLOCK: 'game:clock';
  readonly GAME_OPPONENT_DISCONNECTED: 'game:opponentDisconnected';
  readonly GAME_OPPONENT_RECONNECTED: 'game:opponentReconnected';
  readonly GAME_DRAW_OFFERED: 'game:drawOffered';
  readonly GAME_DRAW_DECLINED: 'game:drawDeclined';
  readonly GAME_ENDED: 'game:ended';
  readonly GAME_ABORT_WARNING: 'game:abortWarning';
  readonly GAME_RESUMABLE: 'game:resumable';
  readonly GAME_REMATCH_OFFERED: 'game:rematchOffered';
  readonly GAME_REMATCH_ACCEPTED: 'game:rematchAccepted';
  readonly GAME_REMATCH_DECLINED: 'game:rematchDeclined';
  readonly GAME_REMATCH_EXPIRED: 'game:rematchExpired';
  readonly OPPONENT_PRESENCE: 'game:opponentPresence';
  readonly PRESENCE_PONG: 'presence:pong';
  readonly ERROR: 'error';
}>;

export type SocketEventName = typeof SocketEvents[keyof typeof SocketEvents];
