name: CI

on:
  pull_request:
    branches: [main, staging]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint-and-build-client:
    name: Lint & Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          package-manager-cache: false

      - name: Update npm
        run: npm install -g npm@11

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  lint-and-build-server:
    name: Lint & Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Update npm
        run: npm install -g npm@11

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Integration Tests
        run: npm run test:integration
